- import_playbook: core.yml

- name: Development Profile
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/texlive/2021/bin/universal-darwin:{{ ansible_env.PATH }}"

  tasks:
    - name: Docker
      import_tasks: tasks/tools/docker.yml

    - name: Tools
      include_tasks: tasks/common/brew_install.yml
      loop:
        - act
        - pyenv
