- import_playbook: core.yml

- name: dotfiles
  hosts: localhost
  connection: local

  vars:
    dotconfig: "{{ ansible_env.HOME }}/.config"

  tasks:
    # WARNING: this will lose any unpushed commits
    # Restore with `git reflog` followed by `git reset --hard [id]`
    - name: Clone dotfiles
      ansible.builtin.git:
        repo: git@github.com:BraeWebb/dotfiles.git
        dest: "{{ dotconfig }}"

    - name: Link files
      ansible.builtin.file:
        src: "{{ dotconfig }}/{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        state: link
      loop:
        - .gitconfig
