- name: Braes Dev Machine
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

  pre_tasks:
    - name: Include vars
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/*.yml"
      tags: ['always']

    - name: Set PATH
      include_tasks: tasks/common/paths.yml
      tags: ['always']

  tasks:
    - import_tasks: tasks/common/brew.yml
      tags: common

    - import_tasks: tasks/files/projects.yml
      tags: projects

    - name: Brew Install
      include_tasks: tasks/common/brew_install.yml
      tags:
        - always
      loop: "{{ brew | dict2items }}"

    - name: Code Install
      import_tasks: tasks/common/code.yml
      tags: common

    - name: Code Extensions Install
      include_tasks: tasks/common/code_install.yml
      tags:
        - always
      loop: "{{ code | dict2items }}"

    - import_tasks: tasks/tools/latex.yml
      tags:
        - tools
        - languages
        - latex

    - import_tasks: tasks/tools/isabelle.yml
      tags:
        - tools
        - languages
        - isabelle

    - import_tasks: tasks/tools/act.yml
      tags:
        - tools
        - devops
        - act

    - import_tasks: tasks/tools/ansible.yml
      tags:
        - tools
        - devops
        - ansible

    - import_tasks: tasks/tools/terraform.yml
      tags:
        - tools
        - devops
        - terraform

    - import_tasks: tasks/tools/nodejs.yml
      tags:
        - tools
        - languages
        - node

    - import_tasks: tasks/tools/react.yml
      tags:
        - tools
        - languages
        - react

    - import_tasks: tasks/tools/plantuml.yml
      tags:
        - tools
        - plant

    - import_tasks: tasks/tools/chrome.yml
      tags:
        - tools
        - chrome

    - import_tasks: tasks/config/wallpaper.yml
      tags:
        - config
        - personal
        - wallpaper

    - import_tasks: tasks/config/workspaces.yml
      tags:
        - config
        - personal
        - workspaces
