- name: Braes Dev Machine
  hosts: localhost
  connection: local

- import_playbook: ansible.yml

- import_playbook: nodejs.yml
- import_playbook: react.yml

- import_playbook: isabelle/isabelle.yml
- import_playbook: isabelle/code.yml
