- import_playbook: core.yml

- name: Braes Dev Machine
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/texlive/2021/bin/universal-darwin:{{ ansible_env.PATH }}"

  tasks:

    - import_tasks: tasks/files/projects.yml
      tags: projects

    - name: Brew Install
      include_tasks: tasks/common/brew_install.yml
      tags:
        - always
      loop: 
        - k6

    - name: Code Extensions Install
      include_tasks: tasks/common/code_install.yml
      tags:
        - always
      loop:
        - redhat.ansible

    - import_tasks: tasks/tools/latex.yml
      tags:
        - tools
        - languages
        - latex

    - import_tasks: tasks/tools/isabelle.yml
      tags:
        - tools
        - languages
        - isabelle

    - import_tasks: tasks/tools/act.yml
      tags:
        - tools
        - devops
        - act

    - import_tasks: tasks/tools/ansible.yml
      tags:
        - tools
        - devops
        - ansible

    - import_tasks: tasks/tools/terraform.yml
      tags:
        - tools
        - devops
        - terraform

    - import_tasks: tasks/tools/nodejs.yml
      tags:
        - tools
        - languages
        - node

    - import_tasks: tasks/tools/plantuml.yml
      tags:
        - tools
        - plant

    - import_tasks: tasks/tools/chrome.yml
      tags:
        - tools
        - chrome

    - import_tasks: tasks/config/wallpaper.yml
      tags:
        - config
        - personal
        - wallpaper

    - import_tasks: tasks/config/workspaces.yml
      tags:
        - config
        - personal
        - workspaces
