- import_playbook: core.yml

- name: Personalization Profile
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: VSCode Extensions
      include_tasks: tasks/common/code_install.yml
      loop:
        - nhoizey.gremlins
        - GitHub.copilot
        - nobuhito.printcode

    - name: Alacritty
      import_tasks: tasks/tools/alacritty.yml

    - name: Terminal tools
      include_tasks: tasks/common/brew_install.yml
      loop:
        - bat
        - git-delta
        - duf
        - fd
        - tldr
        - bottom
        - httpie

    - name: Delta git diff
      blockinfile:
        path: ~/.gitconfig
        block: |
          [core]
              pager = delta

          [interactive]
              diffFilter = delta --color-only

          [delta]
              navigate = true  # use n and N to move between diff sections

          [merge]
              conflictstyle = diff3

          [diff]
              colorMoved = default
