- import_playbook: core.yml

- name: Proving Profile
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/texlive/2021/bin/universal-darwin:{{ ansible_env.PATH }}"

  tasks:
    - name: Tools
      import_tasks: tasks/common/isabelle.yml
