- import_playbook: writing.yml

- name: Teaching Profile
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:/usr/local/texlive/2021/bin/universal-darwin:{{ ansible_env.PATH }}"

  tasks:
    - name: SlidePilot
      homebrew_cask:
        name: slidepilot
