- import_playbook: core.yml

- name: Writing Profile
  hosts: localhost
  connection: local

  vars:
    is_mac: "{{ ansible_distribution == 'MacOSX' }}"

  environment:
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v16.13.1/bin:/home/linuxbrew/.linuxbrew/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: VSCode Extensions
      include_tasks: tasks/common/code_install.yml
      tags:
        - always
      loop:
        - ban.spellright
        - James-Yu.latex-workshop

    - import_tasks: tasks/tools/latex.yml
