---
- name: Install {{ item }}
  tags:
    - test
    - "{{ item }}"

  block:
    - name: Brew install {{ item }}
      homebrew:
        name: "{{ item }}"

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: "{{ item }}"
