---
- name: Install {{ item.key }}
  tags:
    - test
    - "{{ item.key }}"

  block:
    - name: Brew install {{ item.key }}
      homebrew:
        name: "{{ item.key }}"

    - name: "{{ item.key }} version"
      debug:
        msg: "{{ item.value.version }}"
      when: item.value.version is defined

    - name: Version check
      when: "{{ item.key }} is defined"
      include_role:
        name: 'roles/version-check'
      vars:
        tool: "{{ item.key }}"
