---
- name: Install {{ item }} extension
  
  vars:
    ext_version: "{{ lookup('vars', item).version }}"

  block:
    - name: "Install {{ item }} extension"
      command: code --install-extension {{ item }}@{{ ext_version }}
      args:
        creates: "{{ ansible_env.HOME }}/.vscode/extensions/{{ item }}-{{ ext_version }}/package.json"

    - name: "{{ item }} version"
      debug:
        msg: "{{ item + '@' + ext_version }}"

    - name: "{{ item }} version check"
      command: "code --list-extensions --show-versions"
      register: actual_version
      failed_when: 'item + "@" + ext_version not in actual_version.stdout'
      changed_when: false
