---
- name: VSCode
  block:

  - name: Linux Install
    when: not is_mac
    block:
      - name: Add Microsoft APT package key
        become: yes
        apt_key:
          url: https://packages.microsoft.com/keys/microsoft.asc

      - name: Add VS Code APT package repository
        become: yes
        apt_repository:
          repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
          filename: vscode
          update_cache: no
        register: apt_repository

      - name: Update APT package list
        become: yes
        apt:
          update_cache: yes
        when: apt_repository.changed
        register: apt_update
        retries: 5
        until: apt_update is success

      - name: Install VS Code (Linux)
        become: yes
        apt:
          package: code

      - name: Version check
        include_role:
          name: 'roles/version-check'
        vars:
          tool: code

  - name: Install VS Code (macOS)
    when: is_mac
    block:
      - name: Install VS Code (macOS)
        homebrew_cask:
          name: visual-studio-code

      - name: Version check
        include_role:
          name: 'roles/version-check'
        vars:
          tool: code
