---
- name: Git

  block:
    - name: Install git
      become: true
      apt:
        name: git
        state: present
        # update_cache: true

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: git
