---
- name: Git

  block:
    - name: Install git
      become: true
      apt:
        name: git
        state: present
      when: not is_mac # assume xcode tools exist

    - name: Setup git author
      blockinfile:
        path: ~/.gitconfig
        block: |
          [user]
            name = Brae Webb
            email = email@braewebb.com

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: git
