---
- name: Configure paths

  tags: always
  block:
    - name: zsh entrypoint
      lineinfile:
        path: ~/.zshrc
        line: . ~/.bashrc
        create: true

    - name: Add brew to PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
      register: path
      when: not is_mac

    - name: Add texlive to PATH
      lineinfile:
        path: ~/.bashrc
        line: export PATH="/usr/share/texlive:$PATH"
      when: not is_mac

    - name: Add node to PATH
      blockinfile:
        path: ~/.bashrc
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
