---
- name: Act for Github Actions

  block:
    - name: Download act install script
      get_url:
        url: "https://raw.githubusercontent.com/nektos/act/master/install.sh"
        dest: "{{ ansible_install }}/act_install.sh"

    - name: Install act
      script: "{{ ansible_install }}/act_install.sh -b {{ binaries }}"
      become: true
      args:
        creates: "{{ binaries }}/act"

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: act
