---
- name: Ansible
  pip:
    name: ansible-lint[yamllint]

- name: Ansible version check
  command: ansible-lint --version
  register: ansible
  failed_when: 'ansible_lint_version not in ansible.stdout'
  changed_when: false
