---
- name: Isabelle/HOL

  vars:
    isabelle_install: /usr/local/lib/isabelle

  when: isabelle_version is defined

  block:
    - name: Install latex
      import_tasks: latex.yml

    - name: Create install directory
      file:
        path: "{{ ansible_install }}"
        state: directory
        mode: 0755

    - name: Download Isabelle
      get_url:
        url: "https://isabelle.in.tum.de/website-Isabelle{{ isabelle_version }}/dist/Isabelle{{ isabelle_version }}_linux.tar.gz"
        dest: "{{ ansible_install }}/isabelle{{ isabelle_version }}.tar.gz"

    - name: Create Isabelle install directory
      become: true
      file:
        path: "{{ isabelle_install }}"
        state: directory
        mode: 0755

    - name: Unpack Isabelle
      become: true
      unarchive:
        src: "{{ ansible_install }}/isabelle{{ isabelle_version }}.tar.gz"
        dest: "{{ isabelle_install }}"

    - name: Link executable
      become: true
      file:
        src: "{{ isabelle_install }}/Isabelle{{ isabelle_version }}/bin/isabelle"
        dest: "{{ binaries }}/isabelle"
        state: link

    - name: Isabelle version check
      command: isabelle version
      register: isabelle
      failed_when: 'isabelle_version not in isabelle.stdout'
      changed_when: false
