---
- name: Isabelle/HOL

  vars:
    isabelle_install: /usr/local/lib/isabelle
    isabelle_version: "{{ isabelle.version }}"

  block:
    - name: Download Isabelle
      get_url:
        url: "https://isabelle.in.tum.de/website-Isabelle{{ isabelle_version }}/dist/Isabelle{{ isabelle_version }}_linux.tar.gz"
        dest: "{{ ansible_install }}/isabelle{{ isabelle_version }}.tar.gz"

    - name: Create Isabelle install directory
      become: true
      file:
        path: "{{ isabelle_install }}"
        state: directory
        mode: 0755

    - name: Unpack Isabelle
      become: true
      unarchive:
        src: "{{ ansible_install }}/isabelle{{ isabelle_version }}.tar.gz"
        dest: "{{ isabelle_install }}"

    - name: Link executable
      become: true
      file:
        src: "{{ isabelle_install }}/Isabelle{{ isabelle_version }}/bin/isabelle"
        dest: "{{ binaries }}/isabelle"
        state: link

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: isabelle

    # - name: Download Isabelle linter
    #   get_url:
    #     url: "https://github.com/isabelle-prover/isabelle-linter/archive/refs/tags/Isabelle2021-1-v1.0.0.zip"
    #     dest: "{{ ansible_install }}/isabelle-linter.zip"

    # - name: Create Isabelle linter install directory
    #   become: true
    #   file:
    #     path: "{{ isabelle_install }}/Isabelle{{ isabelle_version }}/isabelle-linter"
    #     state: directory
    #     mode: 0755

    # - name: Unpack Isabelle linter
    #   become: true
    #   unarchive:
    #     src: "{{ ansible_install }}/isabelle-linter.zip"
    #     dest: "{{ isabelle_install }}/Isabelle{{ isabelle_version }}/isabelle-linter"

    # - name: Install Isabelle linter
    #   command: isabelle components -u "{{ isabelle_install }}/Isabelle{{ isabelle_version }}/isabelle-linter/isabelle-linter-Isabelle2021-1-v1.0.0"
