---
- name: Latex

  when: latex.version is defined

  block:
    - name: Install latex on linux
      become: true
      apt:
        # update_cache: true
        pkg:
          - libfontconfig1
          - texlive-latex-recommended
          - texlive-latex-extra
          - texlive-fonts-extra
          - texlive-lang-all
          - texlive-bibtex-extra
      when: not is_mac

    - name: Install latex on mac
      homebrew_cask:
        name: mactex
        state: present
      when: is_mac

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: latex

    - name: Chktex
      become: true
      apt:
        pkg:
          - chktex
      when: not is_mac

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: chktex
      when: not is_mac
