---
- name: Terraform

  block:
    - name: Install hashicorp tap
      homebrew_tap:
        name: hashicorp/tap

    - name: Install terraform
      homebrew:
        name: hashicorp/tap/terraform

    - name: Version check
      include_role:
        name: 'roles/version-check'
      vars:
        tool: terraform

    - name: Install Terraform code extension
      command: code --install-extension hashicorp.terraform@2.17.0
      args:
        creates: ~/.vscode/extensions/hashicorp.terraform-2.17.0/package.json
