---
- name: Terraform

  block:
    - name: Install brew
      import_tasks: tasks/common/brew.yml

    - name: Install hashicorp tap
      homebrew_tap:
        name: hashicorp/tap

    - name: Install terraform
      homebrew:
        name: hashicorp/tap/terraform

    - name: Version check
      command: terraform -version
      register: terraform
      failed_when: 'terraform_version not in terraform.stdout'
      changed_when: false
